# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7cde75f4ca941e2593c09f3a8e5ecc414658efd1a05ce1ef19f457466f75025598d260572693b6e607ee7a616f008e483f92da49e26d2cc58e85115006fedefd

test:
  secret_key_base: 11b1979aa34443722907b9ce6272b296964ee2c7ef32d72839cc491553e88c736619dc30c2368345f1c93b696421d28457b30e3b05509e36621c8147808f28bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
